# Site settings
title: "Code, Bike & More"
email: andresilveirah@gmail.com
description: > 
  My personal babbling of every now and then.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codebikeandmore.com"
author: "André Herculano"
about: "/about"
analytics: true
analytics_userid: UA-65138243-1
comments: true
disqus_forum_name: codebikeandmore
logo: "/assets/martin_luther_king.jpg"
social_links:
  - 
    name: github
    url: "https://github.com/andresilveira"
    icon: "github.svg"
  - 
    name: linkedin
    url: "https://de.linkedin.com/in/andresilveirah"
    icon: "linkedin.svg"
  - 
    name: stackoverflow
    url: "http://stackoverflow.com/users/1244883/andré-herculano"
    icon: "stackoverflow.svg"

defaults:
  -
    scope:
      path: ""
    values:
      author: "André Herculano"
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
