# Site settings
title: "Code, Bike & More"
email: andresilveirah@gmail.com
description: > 
  My personal babbling of every now and then.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andresilveira.github.io" # TODO: change to the custom domain
github_username: andresilveira
linkedin_username: andresilveirah
stackoverflow_username: "andré-herculano"
about: "/about"
analytics: true
analytics_userid: UA-65138243-1
comments: true
disqus_forum_name: codebikeandmore

defaults:
  -
    scope:
      path: ""
    values:
      author: "André Herculano"
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
